# Generated by Django 2.1.2 on 2018-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181010_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
